server:
  servlet:
    context-path: /teamachinebackend
  port: 80

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # username: r-bp13wg6c4rk6hn0rio
    password: langtuopassword
    maxIdle: 30 # 连接池中最大空闲链接
    minIdle: 1 # 连接池中最小空闲链接
    maxTotal: 3000 # 控制一个pool可分配多少个jedis实例,用来替换上面的spring.redis.maxActive,如果是jedis 2.4以后用该属性
    maxWaitMillis: 5000 # 最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制

teamachine:
  jwt:
    tokenHeader: Authorization # JWT 存储的请求头
    secret: teamachine-secret # JWT 加解密使用的密钥
    expiration: 604800 # JWT 的超期限时间，单位秒（60 * 60 * 24 * 7）
    tokenHead: 'Bearer '  # JWT 负载中拿到开头
  secure:
    ignored:
      urls: # 安全路径白名单，不包含 tomcat 中 context 的 path（从之后开始算）
        - /swagger-ui/
        - /swagger-resources/**
        - /**/*.html
        - /**/*.js
        - /**/*.css
        - /**/*.png
        - /**/*.map
        - /favicon.ico
        - /actuator/**
        - /druid/**
        - /login/**
        - /logout/**
        - /userset/tenant/list/**
        - /deviceset/machine/activate/**
        - /mqtt/**
        - /summarychart/**
